
steps:
- uses: frankie567/grafana-annotation-action@v1.0.2
    with:
    apiHost: https://myinstance.grafana.net
    apiToken: ${{ secrets.GRAFANA_API_TOKEN }}
    text: Deployment of ${{ github.sha }}
    dashboardId: 1
    tags: deployment,github
